

proxy:
  image: proxy-image
  ports:
    - 80:80
    - 443:443
  links:
    - docssite:docssite
    - mainsite:mainsite

docssite:
  image: docssite-image
            
mainsite:
  image: mainsite-image
  volumes:
    - shouldbehiring.me.docker/shouldbehiring.me/build/content/:/usr/share/shouldbehiring.me/html/content
