

proxy:
  image: proxy-image
  ports:
    - 80:80
    - 443:443
  links:
    - docssite:docssite
    - mainsite:mainsite
    - apiserver:apiserver
  volumes:
    - /etc/letsencrypt/live/hillnetwork.me/fullchain.pem:/etc/letsencrypt/live/hillnetwork.me/fullchain.pem
    - /etc/letsencrypt/live/hillnetwork.me/privkey.pem:/etc/letsencrypt/live/hillnetwork.me/privkey.pem

apiserver:
  image: apiserver-image

docssite:
  image: docssite-image
            
mainsite:
  image: mainsite-image
  volumes:
    - /home/nick/my-webstack/shouldbehiring.me.docker/shouldbehiring.me/build/content/:/usr/share/shouldbehiring.me/html/content
